import { DEMO_KEYS } from "./constants";
import type { Activity, Merchant, Offer, Passport } from "./types";

export const SAMPLE_PASSPORT: Passport = {
  owner: DEMO_KEYS.passportOwner,
  displayName: "Demo member",
  balance: 3_460,
  lifetimePoints: 7_850,
  uniqueMerchants: 4,
  purchaseCount: 18,
  tier: "Silver",
  lastActivity: "2026-07-28T14:24:00.000Z",
};

export const SAMPLE_MERCHANTS: Merchant[] = [
  {
    id: "drift-cycle",
    name: "Drift Cycle",
    shortName: "Drift",
    category: "Mobility",
    authority: "Stake11111111111111111111111111111111111111",
    pointsPerUsdc: 2,
    issuedPoints: 84_920,
    active: true,
    visits: 6,
    spendMinor: 48_200,
    accent: "green",
  },
  {
    id: "northstar-stay",
    name: "Northstar Stay",
    shortName: "Northstar",
    category: "Hospitality",
    authority: "Vote111111111111111111111111111111111111111",
    pointsPerUsdc: 3,
    issuedPoints: 131_400,
    active: true,
    visits: 3,
    spendMinor: 72_800,
    accent: "coral",
  },
  {
    id: "foundry-coffee",
    name: "Foundry Coffee",
    shortName: "Foundry",
    category: "Food",
    authority: "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr",
    pointsPerUsdc: 4,
    issuedPoints: 62_750,
    active: true,
    visits: 7,
    spendMinor: 19_450,
    accent: "gold",
  },
  {
    id: "field-office",
    name: "Field Office",
    shortName: "Field",
    category: "Workspace",
    authority: "AddressLookupTab1e1111111111111111111111111",
    pointsPerUsdc: 2,
    issuedPoints: 97_330,
    active: true,
    visits: 2,
    spendMinor: 31_000,
    accent: "teal",
  },
];

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: 11,
    merchantId: "northstar-stay",
    title: "Priority check-in + lounge",
    description:
      "Skip the front desk and add a two-hour lounge pass to any direct booking.",
    pointsCost: 1_200,
    minTier: "Silver",
    cap: 80,
    redeemed: 31,
    active: true,
    expiresAt: "2026-09-30T23:59:59.000Z",
    label: "Travel",
  },
  {
    id: 7,
    merchantId: "foundry-coffee",
    title: "Coffee flight for two",
    description:
      "Redeem a guided tasting flight with four rotating single-origin coffees.",
    pointsCost: 780,
    minTier: "Bronze",
    cap: 150,
    redeemed: 92,
    active: true,
    expiresAt: "2026-08-31T23:59:59.000Z",
    label: "Popular",
  },
  {
    id: 19,
    merchantId: "drift-cycle",
    title: "Annual service credit",
    description:
      "Apply a service credit to a full tune-up at any coalition Drift workshop.",
    pointsCost: 2_400,
    minTier: "Gold",
    cap: 45,
    redeemed: 12,
    active: true,
    expiresAt: "2026-10-15T23:59:59.000Z",
    label: "Gold",
  },
  {
    id: 4,
    merchantId: "field-office",
    title: "Workspace day pass",
    description:
      "A flexible desk, meeting-room hour, and same-day guest access.",
    pointsCost: 1_400,
    minTier: "Silver",
    cap: 100,
    redeemed: 68,
    active: true,
    expiresAt: "2026-09-15T23:59:59.000Z",
    label: "Limited",
  },
];

export const SAMPLE_ACTIVITY: Activity[] = [
  {
    id: "activity-1",
    kind: "purchase",
    merchantId: "foundry-coffee",
    title: "Receipt accepted",
    detail: "$42.00 purchase · 4 points/USDC · 7.5% coalition bonus",
    timestamp: "2026-07-28T14:24:00.000Z",
    points: 180,
    receiptHash: "4c6f7961...303031",
    verified: true,
  },
  {
    id: "activity-2",
    kind: "redemption",
    merchantId: "northstar-stay",
    title: "Offer redeemed",
    detail: "Late checkout · redemption nonce 2",
    timestamp: "2026-07-24T09:08:00.000Z",
    points: -950,
    receiptHash: "9f3b2d11...e702a4",
    verified: true,
  },
  {
    id: "activity-3",
    kind: "merchant",
    merchantId: "field-office",
    title: "New merchant discovered",
    detail: "Fourth coalition merchant · network bonus increased to 7.5%",
    timestamp: "2026-07-18T16:42:00.000Z",
    points: 0,
    receiptHash: "eb28c031...7ac490",
    verified: true,
  },
  {
    id: "activity-4",
    kind: "tier",
    title: "Silver tier reached",
    detail: "Lifetime balance crossed the 2,500-point threshold",
    timestamp: "2026-06-29T11:15:00.000Z",
    points: 0,
    verified: true,
  },
];
